---
language: ruby
script:
    - 'cd test/dummy && rake db:migrate db:test:prepare'
    - rake test
rvm:
  - '1.9.3'
  - '2.0.0'

env:
  - DB=sqlite                     RAILS='~> 4.0'
  - DB=mysql                      RAILS='~> 4.0'
  - DB=sqlite FORMTASTIC='~> 2.2' RAILS='~> 3.2'
  - DB=sqlite FORMTASTIC='~> 2.2' RAILS='~> 4.0'

matrix:
  exclude:
    - rvm: 1.9.3
      env: DB=mysql RAILS='~> 4.0'
    - rvm: 1.9.3
      env: DB=sqlite FORMTASTIC='~> 2.2' RAILS='~> 4.0'


before_script:
  - mysql -e 'create database myapp_test'
  - psql -c 'create database myapp_test' -U postgres
  - rake dummy:setup
  - rake app:db:migrate
  - rake app:db:migrate RAILS_ENV=test
